"""Update User_Game table to display username + game word

Revision ID: 1b81f247c0a2
Revises: 3a530fc4b69f
Create Date: 2023-07-19 15:46:52.028218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b81f247c0a2'
down_revision = '3a530fc4b69f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_games_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_user_games_game_id_game', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_games_game_id_game', 'game', ['game_id'], ['id'])
        batch_op.create_foreign_key('fk_user_games_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
