"""Holy im gonna blow my brains outttt

Revision ID: 3c501b7574ab
Revises: 47910418900d
Create Date: 2023-07-18 16:58:06.814598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c501b7574ab'
down_revision = '47910418900d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user_games_game_id_game'), 'game', ['game_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_games_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_games_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_games_game_id_game'), type_='foreignkey')

    # ### end Alembic commands ###
